### PR TITLE
Update application links

### PR DESCRIPTION
**Pull request by mvgeorgescu**
@RaeChen07 - I updated the use of `<ListGroup>` by wrapping it in a `<LinkContainer>`. This is a component that I found in the project https://github.com/react-bootstrap/react-router-bootstrap which is developed by the react-bootstrap developers to bring compatibility of react-router to react-bootstrap. I could use some help QA'ing the change. I checked the following:
 - The update preserves styling of the ListGroup links (incl. hover effects)
 - If I click on a job, navigate to a different page, and navigate back to the job, the information I entered previously is preserved.

### CODE REVIEW

**Comment by RaeChen07** [comment]
Looks good to me. I think we can safely delete the action in ListGroup, thanks ;)

**Review by RaeChen07 — APPROVED** [review]

**Review by jackcruz53 — APPROVED** [review]
Lgtm!

**Comment by RaeChen07** [comment]
> @RaeChen07 - I actually need to have some truthy value for the action property otherwise I believe it defaults to `false`, and with that, removes some formatting and highlighting on hover.
> 
> Instead of `action href={`/app/${key}`}` I can instead specify `action={true}`. Would you prefer that instead since it de-dupes the url?

action={true} for now is fine, I think I'll figure a css out later, thanks

**Review by charliepnnl — APPROVED** [review]
react-router-bootstrap was a good find!

**Review by RaeChen07 — APPROVED** [review]

**Review by jackcruz53 — APPROVED** [review]
Just verified the changes, LGTM!

**Pull request merged**
